version: '3'
services:
  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml
  prometheus:
     image: prom/prometheus:v2.28.1
     container_name: prometheus
     restart: unless-stopped
     volumes:
       - ./prometheus:/etc/prometheus
     ports:
       - 9090:9090
     command:
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--storage.tsdb.path=/prometheus'
     - '--storage.tsdb.retention.time=1y'
     - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
